name: "CI"
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.17.0"
      - name: Install packages
        run: npm install
      - name: Run Truffle Test with CI=true for Codechecks  
        run: CI=true npm run test
      - name: coverage
        run: npm run coverage 
      - name: solhint
        run: npm run solhint 

      